### ISSUE TITLE
Work with the QuizCategory and import/export this object, instead of the List

### ISSUE THREAD

**Issue by mayisa87** [Marko-Pajic/QuizMaker#23]
https://github.com/Marko-Pajic/QuizMaker/blob/4ee6ef0489940bc240a782b8de6936590cd3fb3a/FileUtils.cs#L25

We did discuss this already in WA, from my point of view it would make much more sense to directly export and import the whole category object, instead of using the List with questions. As this object will hold the list and category attributes too.

And it will really simplify your code a lot!

**Comment by Marko-Pajic** [comment]
<img width="770" alt="Skärmbild 2023-12-13 234621" src="https://github.com/Marko-Pajic/QuizMaker/assets/135176187/89df6a71-d28a-45cc-bdc3-f0f7dfbc6ed3">
Im sorry Isabella but i dont understand how im still importing only lists. I did forget to erase List as method parameter and that commented out List<Question> on line 33 but method is not using that,right?.
